name: lib_calculatr
description: A simple ast-based math solver
version: 1.0.0
repository: https://github.com/BoseVJeff/lib_calculatr

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  meta: 1.11.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
